#Make a major request
GET http://localhost:2000

###

###
#Add Category
POST http://127.0.0.1:2000/api/v1/category
Content-Type: application/json

{
    "name": "Shoes",
    "color": "Black",
    "icon": "Boot-icon",
    "image": "text of an image"

}
###
#Delete Category By ID
DELETE http://127.0.0.1:2000/api/v1/category/


#get Category
#get Single Category
###
GET http://127.0.0.1:2000/api/v1/category/

#Update Category
###

PUT http://127.0.0.1:2000/api/v1/category/61825f427ae6ccb27277b57c
Content-Type: application/json

{
    "name": "New Cars",
    "color": "Golden",
    "icon": "car-icon",
    "image": "New Image has been uploaded"
}

###
#add a Product
POST http://localhost:2000/api/v1/product
Content-Type: application/json

{
    "name":"Compact",
    "description": "Compact Resolve has value",
    "richDescrption": "Understanding the step is worth the kill",
    "image": "This is a Compact resolve image",
    "images": "More Image",
    "brand": "Nike",
    "Price": 120000,
    "category": "shoes",
    "countInStock": 92,
    "rating": 5,
    "numReview": 12,
    "isFeatured": true
}


###
#Get Single Product by :id
GET http://localhost:2000/api/v1/product/618274e62faceb8cdc940b0b

###
#Get all Product 
GET http://localhost:2000/api/v1/product

###
#Get all product by category id
GET http://localhost:2000/api/v1/product?category=6182739592bb0f9cadb45473

###
#Update the product
PUT http://localhost:2000/api/v1/product/618274e62faceb8cdc940b0b
Content-Type: application/json

{
    "name":"Nike Resolve Cardio",
    "description": "Nike Resolve has value",
    "richDescrption": "Understanding the step is worth the kill",
    "image": "This is a nike resolve image",
    "images": "More Image",
    "brand": "Nike",
    "Price": 120000,
    "category": "shoes",
    "countInStock": 92,
    "rating": 5,
    "numReview": 12,
    "isFeatured": true
}



###
#Get Featured Product
GET http://localhost:2000/api/v1/product/featured

###
#USER USER 

#Register User

POST http://localhost:2000/api/v1/user/register
Content-Type: application/json

{"name":"Divines okezie",
"email": "Divinesokezie76@gmail.com",
"password": "123",
"street": "HR Street",
"apartment": "HR 2 ORC",
"city":"P-H",
"zip":"90099",
"country": "Nigeria",
"phone": "08075103883",
"isAdmin": true
}


###
#Get all User

GET http://localhost:2000/api/v1/user/


###
#Login in user data
POST http://localhost:2000/api/v1/user/login
Content-Type: application/json

{
    "email": "Danielokezie75@gmail.com",
    "password": "123"
}

#ORDER 
###
POST http://localhost:2000/api/v1/order
Content-Type: application/json

{
    "orderitem": "Addidas Resolve",
    "quantity": 2,
    "shippingaddress": "Street one",
    "shippingaddress2": "Street Two",
    "city": "Abuja",
    "zip": "90099",
    "country": "Tree man Country",
    "phone": 123456789,
    "totalPrice": 12.2,
    "user": "Daniel Okezie"
}